### PR TITLE
Allow AwsDriver to work even if you haven't explicitly required 'chef/pr...

### PR DESCRIPTION
**Pull request by jkeiser**
...ovisioning/aws_driver'

### CODE REVIEW

**Comment by jkeiser** [comment]
CC @tyler-ball @fnichol

**Comment by tyler-ball** [comment]
Rebasing to get Travis to pass.  Otherwise, :+1:

**Comment by dblessing** [comment]
Does it work to load the driver if no aws config exists? When we put our recipe together the chef run failed at compile time because aws config didn't exist yet.

**Comment by tyler-ball** [comment]
I get `[2015-04-06T17:51:06-05:00] ERROR: No credentials loaded!  Do you have a ~/.aws/config?` if I don't have credentials, and it is a compile time bug.  @jkeiser is this the intended behavior?  @dblessing is your desire to have the recipe only fail if a call to AWS is attempted?  IE, we lazy load the credentials the first time an AWS call is attempted.

**Comment by dblessing** [comment]
Lazy load would be great. Then the first part of recipe manage the configuration before any provisioning resources.

**Comment by tyler-ball** [comment]
@dblessing Will you file a new issue on lazy loading?

**Comment by dblessing** [comment]
Yep, I created one a while back. #145

**Pull request merged**
