### PR TITLE
Check existing_sg not existing_vpc in security group delete

### PR DESCRIPTION
**Pull request by christinedraper**
Fixes issue #74

### CODE REVIEW

**Comment by tyler-ball** [comment]
:+1: This seems pretty obvious - good catch!

**Comment by tyler-ball** [comment]
@christinedraper I rebased and squashed down to 1 commit - thats why this isn't automatically linking.  Manually closing, but it did get merged in!

**Comment by christinedraper** [comment]
Thanks..  still getting up to speed with submitting pull requests, sorry for the extra commits.

**Comment by tyler-ball** [comment]
No worries!  Running an interactive rebase (`rebase -i`) allows you to squash commits together so the log is shorter.  For small changes like this, I prefer to do that.  It keeps the history from growing too huge.

**Pull request closed without merging**
