### PR TITLE
support a health_check stanza, just like we handle an ELB's native attributes, fixes #107

### LINKED ISSUE #107: Allow specifying health check on ELB
http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/Client.html#configure_health_check-instance_method

### PR DESCRIPTION
**Pull request by redterror**
Fixes #107.

### CODE REVIEW

**Comment by danieljimenez** [comment]
+1 I tested on my test and staging cluster, worked great.

**Comment by tyler-ball** [comment]
Hey @redterror - this code LGTM.  Will you update https://github.com/chef/chef-provisioning-aws/blob/master/docs/examples/load_balancer.rb#L40-L64 to include an example of what this looks like and then run that locally to ensure it still works?

We also need to add a test for this.  Will you create a `load_balancer_spec.rb` file and add the following contents:

```ruby
describe "load_balancer" do
  extend AWSSupport

  when_the_chef_12_server "exists", organization: 'foo', server_scope: :context do
    with_aws "when connected to AWS" do
      
      setup_vpc
      
      az = test_public_subnet.aws_object.availability_zone_name

      it "creates a load_balancer with the maximum attributes" do
        expect_recipe {
          load_balancer 'test-load-balancer' do
            load_balancer_options({
              listeners: [{
                  :port => 80,
                  :protocol => :http,
                  :instance_port => 80,
                  :instance_protocol => :http,
              }],
              availability_zones: [az],
              subnets: ["test_public_subnet"],
              security_groups: ["test_security_group"],
              health_check: {
                target: "TCP:8080",
                interval: 10,
                timeout: 5,
                unhealthy_threshold: 1,
                healthy_threshold: 1
              }
           })
          end
        }.to create_an_aws_load_balancer('test-load-balancer', {
          listeners: [{
              :port => 80,
              :protocol => :http,
              :instance_port => 80,
              :instance_protocol => :http,
          }],
          availability_zones: [az],
          subnets: [test_public_subnet.aws_object.id],
          security_groups: [test_public_subnet.aws_object.id],
          health_check: {
            target: "TCP:8080",
            interval: 10,
            timeout: 5,
            unhealthy_threshold: 1,
            healthy_threshold: 1
          }
        }
        ).and be_idempotent
      end

    end
  end
end
```

I haven't tested that so it may not work immediately, but let me know if it doesn't and I can help troubleshoot.

Thanks!

**Comment by redterror** [comment]
I got a start on the specs, but hit a wall with getting the specifics correct in the test.  The listeners are returned as a `AWS::ELB::ListenerCollection` but the spec is expecting an Array.  I wasn't sure how to handle the conversion there.  That said, it did the right thing:

```
Chef::Resource::LoadBalancer
  When the Chef server exists
    when the chef repo exists and with a VPC and a public subnet
* aws_key_pair[test_key_pair] action purge (up to date)
* aws_vpc[test_vpc] (no AWS object id) action create
  - waited 0/300s for vpc-9a6d17ff state to change to [:available]...
  - create VPC test_vpc in us-west-2
  - create data bag aws_vpc at http://127.0.0.1:8900/organizations/foo
  - create data bag item test_vpc at http://127.0.0.1:8900/organizations/foo
  -   add reference = {"id"=>"vpc-9a6d17ff"}
  -   add driver_url = "aws"
  - update enable_dns_hostnames to true (was false) in VPC test_vpc (vpc-9a6d17ff)
  - create Internet gateway igw-946fedf1
  - tag Internet gateway igw-946fedf1 as OwnedByVpc: vpc-9a6d17ff
  - attach Internet gateway to VPC vpc-9a6d17ff
* aws_route_table[rtb-71793914] (rtb-71793914) action create
  - route 0.0.0.0/0 to internet_gateway (igw-946fedf1)
* aws_key_pair[test_key_pair] action create
  - create test_key_pair on aws from local key at
* aws_security_group[sg-75c74011] action create
  - authorize 0.0.0.0/0 to send traffic to group sg-75c74011 (sg-75c74011) on port_range 22..22 with protocol tcp
  - revoke the ability of sg-75c74011 to send traffic to group sg-75c74011 (sg-75c74011) on port_range -1..-1 with protocol -1
* aws_subnet[test_public_subnet] (no AWS object id) action create
  - create subnet test_public_subnet with CIDR 10.0.0.0/24 in VPC test_vpc (vpc-9a6d17ff) in us-west-2
  - create data bag aws_subnet at http://127.0.0.1:8900/organizations/foo
  - create data bag item test_public_subnet at http://127.0.0.1:8900/organizations/foo
  -   add reference = {"id"=>"subnet-f9fa948e"}
  -   add driver_url = "aws"
  - turn on automatic public IPs for subnet subnet-f9fa948e
* load_balancer[test-load-balancer] action create
  - create load balancer test-load-balancer in us-west-2
  -   attach subnets subnet-f9fa948e
  -   with listeners [{:port=>80, :protocol=>:http, :instance_port=>80, :instance_protocol=>:http}]
  -   with security groups ["sg-75c74011"]
  -   updating health check to {:unhealthy_threshold=>2, :interval=>10, :healthy_threshold=>2, :timeout=>5, :target=>"HTTP:80/"}
  - create data bag load_balancer at http://127.0.0.1:8900/organizations/foo
  - create data bag item test-load-balancer at http://127.0.0.1:8900/organizations/foo
  -   add reference = {"driver_version"=>"1.4.0.dev.1", "allocated_at"=>"2015-09-09 19:39:55 UTC"}
  -   add driver_url = "aws"
      creates a load_balancer with the maximum attributes (FAILED - 1)

```

**Comment by tyler-ball** [comment]
@redterror I'll take a look at it tomorrow and see if I can figure out whats going on!

**Comment by tyler-ball** [comment]
Merged in 129ab0fce825176299bc1b3155c25aae3fe5f94a, it didn't close this automatically because I had to rebase

**Pull request closed without merging**
