### PR TITLE
Fix specs

### PR DESCRIPTION
**Pull request by erikvanbrakel**
Support for 'with_driver' and 'driver' (PR #111) broke the recently added specs. This seems to fix it, but is there a better way?

### CODE REVIEW

**Comment by jkeiser** [comment]
@erikvanbrakel probably the best way is to modify the `run_context` at the top there, so you (hopefully) don't have to do that:

```ruby
run_context.chef_provisioning.with_driver 'aws'
```

I'm OK merging this too; let me know what you'd like to do :)

**Comment by erikvanbrakel** [comment]
I'll change the run context. Was actually looking for that, but I am not that good at chef or ruby yet, so I couldn't find it ;-)

Op 2 mrt. 2015 19:09 schreef John Keiser <notifications@github.com>:

@erikvanbrakel<https://github.com/erikvanbrakel> probably the best way is to modify the run_context at the top there, so you (hopefully) don't have to do that:

run_context.chef_provisioning.with_driver 'aws'

I'm OK merging this too; let me know what you'd like to do :)

**Comment by erikvanbrakel** [comment]
Decided to change the run_context where it's initialized, as it's also used by the provider. Probably cleanest option now.

**Comment by erikvanbrakel** [comment]
Hmm, identified another issue with the specs, which is a blocker for this PR: AWS is not being stubbed anymore. I believe AWS.stub! sets a default config setting, but as we create a new config object in lib/chef/provisioning/driver.rb:50, this is ignored. Will try to fix this...

**Comment by erikvanbrakel** [comment]
There, that should do it.

**Pull request closed without merging**
