### PR TITLE
Added aws_nat_gateway resource and provider

### PR DESCRIPTION
**Pull request by tyler-ball**
Creating this to replace https://github.com/chef/chef-provisioning-aws/pull/434 .  I had some review changes I made and didn't want to create a PR to merge those into a fork. So now lets just work out of this PR!

I think the existing PR looks great. The one big change I made is to not try and manage an EIP automatically from within a NAT gateway. The SDK support is too limited to do that effectively (neither of the objects support tags).  So recipe authors will have to manage their EIP addresses separately.

\cc @joaogbcravo @jgoulah @djapg @jeffbyrnes

### CODE REVIEW

**Comment by tyler-ball** [comment]
@joaogbcravo I didn't update the tests to reflect that we don't want to automatically manage EIP addresses. Would you mind updating those tests and running them? If they all pass then this is good to merge

**Comment by joaogbcravo** [comment]
@tyler-ball I'm sad with that EIP managing being removed, but I can understand your thought. Hopefully AWS enables tagging on EIP and we can change the way that is done.

As soon as I have some time, I will review the tests and will merge it.

**Comment by tyler-ball** [comment]
Test failures are un-related, going ahead and merging this

**Comment by djapg** [comment]
Yay thank you!!

**Pull request merged**
