### PR TITLE
AWS Proxy & Session Token Support

### PR DESCRIPTION
**Pull request by afiune**
As a Enterprise User I need to be able to tell chef-provisioning to use my corporate proxy and also my session token so I can pass-through and reach Amazon EC2.

cc/ @jonsmorrow @mfdii @jkeiser

### CODE REVIEW

**Comment by smford22** [comment]
+1

**Comment by afiune** [comment]
Added some test! :smile:

**Comment by afiune** [comment]
@jkeiser any update on this PR?

**Comment by jonsmorrow** [comment]
+1

**Comment by jkeiser** [comment]
:+1:

**Pull request merged**
