### PR TITLE
Used managed entries for data bags, make resources responsible for referencing their object and entry

### PR DESCRIPTION
**Pull request by jkeiser**

### CODE REVIEW

**Comment by tyler-ball** [comment]
Hey @jkeiser - I'm up to date with https://github.com/chef/chef-provisioning-aws/commit/9a00c2b73de0e92af8313d4a1ce438e9622c3308 and I'm seeing an error with the following recipe (slimmed down version of my ref.rb recipe, with custom names):

```ruby
require 'chef/provisioning/aws_driver'
with_driver 'aws::us-west-2'

aws_vpc 'vpc-tball-vpc' do
  cidr_block '10.0.0.0/24'
end

aws_subnet 'subnet-tball-subnet' do
  vpc 'vpc-tball-vpc'
  map_public_ip_on_launch true
end

machine_image 'tball-machine_image3' do
  machine_options bootstrap_options: {
    subnet_id: 'subnet-tball-subnet'
end
```

The stacktrace I am seeing is:
```
1) NoMethodError -  machine_image[tball-machine_image3] (test-provisioning::default line 47) had an error: NoMethodError: undefined method `chef_provisioning' for nil:NilClass
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/aws_resource.rb:21:in `block in <class:AWSResource>'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/super_lwrp.rb:15:in `instance_exec'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/super_lwrp.rb:15:in `block in attribute'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/aws_resource.rb:65:in `get_aws_object'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/aws_resource.rb:71:in `get_aws_object_id'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/aws_resource.rb:51:in `block in lookup_options'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/aws_resource.rb:43:in `each'
```

But the reason this is happening is because the Subnet is being initialized with a nil run_context - when I put `require 'pry'; binding.pry if run_context.nil?` at https://github.com/chef/chef-provisioning-aws/blob/b8359be5aaf7b503181f3072634ef9bfd5b70c93/lib/chef/provisioning/aws_driver/aws_resource.rb#L9 the run_context is passed in as nil when trying to create the `machine_image` resource.  The subnet is created successfully from its own resource.

**Comment by jkeiser** [comment]
@tyler-ball I have fixed all issues there.  Sometimes the resources do get initialized with `nil` run_contexts (particularly when the driver opens it up, it has no `run_context` to pass).  The code we have here shouldn't be relying on it, only using `driver` and `managed_entry_store`.

**Comment by jkeiser** [comment]
Also added a full destroy recipe, and verified launch_configuration and auto_scaling_group.

**Comment by jkeiser** [comment]
All resources verified to:
1. Create the first time (`ref.rb`)
2. Reference each other (all known references to other objects in the system are in `ref.rb`).
3. Do nothing and display (up to date) the second time (except security group due to a known issue with a separate PR)
4. Successfully destroy (`destroy_ref.rb`)

I'mma leave it now :)

**Comment by tyler-ball** [comment]
I had 1 minor issue that I added a fix for, but otherwise the ref.rb and destroy.rb recipes work!  I think there is some cleanup we could do but I'm going to go ahead and merge this - thanks for the awesome work, @jkeiser!

**Pull request merged**
