### PR TITLE
Fix ignoring convergence_options

### PR DESCRIPTION
**Pull request by BGmot**
Fixes issue https://github.com/chef/chef-provisioning-aws/issues/534

### CODE REVIEW

**Comment by tyler-ball** [comment]
Can you confirm if merging #532 fixed your issue?

**Comment by BGmot** [comment]
@tyler-ball yes, it does fix this issue.

**Comment by jgoulah** [comment]
can someone please apply this?

**Comment by jgoulah** [comment]
I think this can be closed because I believe this works properly in chef-provisioning-aws 2.2.2

**Comment by tas50** [comment]
Closing per @jgoulah

**Pull request closed without merging**
