### PR TITLE
AWS Provisioner does not work correctly with Machine_batch

### PR DESCRIPTION
**Pull request by lynchc**
If you create a series of machines surrounded with a machine_batch, they will not be created in parallel. The allocate_machine method will be executed from multiple threads and will fail with Argument errors on actual_instance.exists?

A quick solution was to add in a mutex to the method. It would still not be ran in parallel but would create safety to avoid failures.

After discussion with @johnewart, he decided that the best solution was to have the aws driver implement it's own version of allocate_machines that accepts and uses the cheffs parallelizer correctly

### CODE REVIEW

**Comment by lynchc** [comment]
This is the link to the aws discussion explaining how the ruby sdk isn't thread safe and how to circumvent:
https://forums.aws.amazon.com/thread.jspa?threadID=100212

**Comment by jkeiser** [comment]
:+1: looks just like the fog one.

**Comment by jkeiser** [comment]
Checked in as a4d6f75

**Comment by lynchc** [comment]
The best ideas are the ones you steal from people who are smarter than you

**Pull request closed without merging**
